apiVersion: v1
kind: Pod
metadata:
  name: active-incident
  labels:
    app.kubernetes.io/name: active-incident
spec:
  volumes:
    - name: active-incident-data-volume
      persistentVolumeClaim:
        claimName: active-incident-storage
        readOnly: false
  containers:
    - name: active-incident-container
      image: us-central1-docker.pkg.dev/mchirico/public/activeincident:v0.0.2
      volumeMounts:
        - mountPath: /data
          name: active-incident-data-volume
  restartPolicy: Always
