apiVersion: v1
kind: Pod
metadata:
  name: active-incident
  labels:
    app.kubernetes.io/name: active-incident
spec:
  volumes:
    - name: active-incident-data-volume
      persistentVolumeClaim:
        claimName: active-incident-storage
        readOnly: false
  containers:
    - name: active-incident-container
      image: us-central1-docker.pkg.dev/mchirico/public/etcd:v0.0.1
      command: ["/bin/etcd"]
      args: ["--client-cert-auth","--trusted-ca-file",
      "/etc/config/ca.pem","--cert-file","/etc/config/etcd-certs.pem","--key-file",
      "/etc/config/etcd-certs-key.pem","--peer-trusted-ca-file","/etc/config/ca.pem",
      "--advertise-client-urls","https://0.0.0.0:2379",
      "--listen-client-urls","https://0.0.0.0:2379",
      "--data-dir=/data"]
      volumeMounts:
        - mountPath: /data
          name: active-incident-data-volume
  restartPolicy: Always
